### ISSUE TITLE
Error #1007: Instantiation attempted on a non-constructor.

### ISSUE THREAD

**Issue by Shaunmax** [GameAnalytics/GA-SDK-AIR#10]
When trying to initialize i am getting the following error 

`[Fault] exception, information=TypeError: Error #1007: Instantiation attempted on a non-constructor.`

```
GameAnalytics.config
.setAutoDetectAppVersion(true)
.setResourceCurrencies(new ["gems", "coins"])
.setGameKeyAndroid("xxxxxxxx")
.setGameSecretAndroid("xxxxxxxxx");

if(GameAnalytics.init())
{
// SDK has been initialized correctly now
GameAnalytics.addDesignEvent("Game:Started");
}
```

When I remove the line `.setResourceCurrencies(new ["gems", "coins"])` the error is gone! 
What is the issue with .`setResourceCurrencies(new ["gems", "coins"])` in the above code.

Also in the editor i can see red under line : - 

![Screen Shot 2020-09-15 at 10 29 07 PM](https://user-images.githubusercontent.com/16576562/93241580-2c1c3f00-f7a3-11ea-97d3-de19f71901b2.png)

but code compiles with no issue!

**Comment by the1schwartz** [comment]
Ok what happens if you replace 'new ["coins", "diamonds"]' with 'new <String>["coins", "diamonds"]'?

**Comment by the1schwartz** [comment]
The documentation page has been updated to show the correct way. Let me know if it helps.

**Comment by Shaunmax** [comment]
> The documentation page has been updated to show the correct way. Let me know if it helps.

That fixed the issue! thanks a lot!
