### ISSUE TITLE
Progressive Events not working when used all parameters

### ISSUE THREAD

**Issue by ravio64344** [GameAnalytics/GA-SDK-AIR#2]
Hi,
I am using this ane for my game in iOS.
My issue is when i use progressive events with all four parameters it not get reflected on Game Analytics. But when i only use Two parameters it get reflected.
Please help me out in that.

For Eg. if i use this type it not show in Game Analytics
GameAnalytics.addProgressionEvent(GAProgressionStatus.START, "level Start","Level 1","",0); 
GameAnalytics.addProgressionEvent(GAProgressionStatus.COMPLETE, "level Completed","Level 1","",10); 

But it works on like this,
GameAnalytics.addProgressionEvent(GAProgressionStatus.START, "level Start"); 
GameAnalytics.addProgressionEvent(GAProgressionStatus.COMPLETE, "level Completed");

Thanks.

**Comment by the1schwartz** [comment]
Hi,

Thanks for reporting this bug. We have made a new release now which should fix this issue, so now you should call progression events like this:

GameAnalytics.addProgressionEvent(GAProgressionStatus.START, "world1", "level1", "phase1");
GameAnalytics.addProgressionEvent(GAProgressionStatus.COMPLETE, "world1", "level1", "phase1", 100);
GameAnalytics.addProgressionEvent(GAProgressionStatus.START, "world1", "level1");
GameAnalytics.addProgressionEvent(GAProgressionStatus.COMPLETE, "world1", "level1", 100);
GameAnalytics.addProgressionEvent(GAProgressionStatus.START, "world1");
GameAnalytics.addProgressionEvent(GAProgressionStatus.COMPLETE, "world1", 100);

Kind regards,
Martin
Lead SDK Developer @ GameAnalytics
