### ISSUE TITLE
Android 64-Bit

### ISSUE THREAD

**Issue by inovento** [GameAnalytics/GA-SDK-AIR#3]
Hello,

We would like to integrate the GameAnalytics service into our new game on Android but we can now publish on GooglePlay only if all included ANEs support the 64-bit Android platform that has been made available through Adobe/Harmann AIR SDK 33.

So far the GA SDK ANE has not been updated to include the 64-bit Android code and would like to ask whether you have plans to make it available anytime in the future.

We're sure that all AIR community actively using or planning to use GameAnalytics in their AIR projects will highly appreciate your efforts.

Thanks!

**Comment by the1schwartz** [comment]
Ok thanks for the feedback. I have updated the version to use AIR SDK 33 in the latest version (v.2.1.4)

**Comment by inovento** [comment]
Thank you for looking into this.
We downloaded the latest version but the platform implementation for Android-ARM64 is missing in the package. The platforms that are included are Android-ARM, Android-x86, iPhone-ARM, MacOS-x86-64 and Windows-x86.

**Comment by the1schwartz** [comment]
Ah sorry that should be fixed now in the latest version (v2.1.5)

**Comment by inovento** [comment]
Thank you very much for the great support @the1schwartz ! 

Only we came across a compilation error due to a change in the extension namespace to 
<extension xmlns="http://ns.adobe.com/air/extension/33.0">
In AIR SDK 33 the extension version is still 32.0 and hasn't been changed so far by Harmann.

**Comment by the1schwartz** [comment]
Ah ok thanks I will change back to 32 then instead of 33.
