### ISSUE TITLE
Error while packaging ipa: Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by kalashot** [GameAnalytics/GA-SDK-AIR#5]
Hi, I have got an error while packaging ipa with the latest (3.0.3) version of GA sdk:

Undefined symbols for architecture arm64:
  "_ga_getConfigurationsContentAsString", referenced from:
      _AIRGameAnalytics_extFunctions in C:\Users\kalashot\AppData\Local\Temp\f1e
73289-adf9-4a54-b37f-29e7a7fc206f\libcom.gameanalytics.sdk.a(AIRGameAnalytics.o)

ld: symbol(s) not found for architecture arm64
Compilation failed while executing : ld64

I have no such error with the previous version(from summer 2019) of ANE.

My config: Windows/Flashdevelop/Adobe air 33.0.2.315 with libclang_rt.ios.a in [AIRSDK_PATH]/lib/aot/lib/

**Comment by the1schwartz** [comment]
Ok thanks for reporting that. It should now be fixed in the latest version (v3.0.4)

**Comment by rubel** [comment]
I just simply create a new document, add the extension and try to compile. And receive the folowing error message from compiler

invalid input.

Undefined symbols for architecture arm64:
  "_ga_getABTestingId", referenced from:
      _AIRGameAnalytics_extFunctions in libcom.gameanalytics.sdk.a(AIRGameAnalytics.o)
  "_ga_getABTestingVariantId", referenced from:
      _AIRGameAnalytics_extFunctions in libcom.gameanalytics.sdk.a(AIRGameAnalytics.o)
  "_ga_onQuit", referenced from:
      _AIRGameAnalytics_extFunctions in libcom.gameanalytics.sdk.a(AIRGameAnalytics.o)
ld: symbol(s) not found for architecture arm64


I am working in adobe flash cc, air 33 (from harman)

**Comment by dampgnat** [comment]
Hi @the1schwartz, I'm having the same issue when packaging to iOS.  (Windows and Android package and run fine).

Undefined symbols for architecture armv7:
"_ga_addAdEvent", "_ga_addAdWithDurationEvent" and "_ga_addAdWithNoAdReasonEvent"

Undefined symbols for architecture arm64:
"_ga_addAdEvent", "_ga_addAdWithDurationEvent" and "_ga_addAdWithNoAdReasonEvent"

I'm using the latest versions of FlashDevelop, Harman 33.1.1.300 and GA-SDK-AIR v3.3.4

**Comment by the1schwartz** [comment]
Thanks for reporting this. This should be fixed in the latest version now (v3.3.5)

**Comment by dampgnat** [comment]
Thank you so much for the super quick fix! Works a treat :) Amazing tool!
(btw fyi I notice that received events report device:"iPhone8, 1" while I'm testing on an iPhone6S)

**Comment by the1schwartz** [comment]
Ok to great to hear. Yeah "iPhone8, 1" is apparently iPhone 6S machine id as listed here: https://gist.github.com/adamawolf/3048717
