### ISSUE TITLE
Update Marpies ANEs to support 64Bits

### ISSUE THREAD

**Issue by goodamr** [GameAnalytics/GA-SDK-AIR#7]
Please update the following Marpies ANEs to support 64Bits:
com.marpies.ane.googleplayservices.ads
com.marpies.ane.googleplayservices.basement

**Comment by the1schwartz** [comment]
Hi, thanks for reporting this. Recently we have refactored the native android library to not be dependent anymore on those libraries, so you don't need to add the anymore. The documentation page has also been updated and the .ane files has been removed from this repo.
