### ISSUE TITLE
Compile error (framework issue)

### ISSUE THREAD

**Issue by rubel** [GameAnalytics/GA-SDK-AIR#8]
I just simply create a new document, add the extension and try to compile. And receive the folowing error message from compiler

invalid input.

Undefined symbols for architecture arm64:
  "_ga_getABTestingId", referenced from:
      _AIRGameAnalytics_extFunctions in libcom.gameanalytics.sdk.a(AIRGameAnalytics.o)
  "_ga_getABTestingVariantId", referenced from:
      _AIRGameAnalytics_extFunctions in libcom.gameanalytics.sdk.a(AIRGameAnalytics.o)
  "_ga_onQuit", referenced from:
      _AIRGameAnalytics_extFunctions in libcom.gameanalytics.sdk.a(AIRGameAnalytics.o)
ld: symbol(s) not found for architecture arm64

I am working in adobe flash cc, air 33 (from harman)

**Comment by the1schwartz** [comment]
Thanks for reporting this. This should be fixed now in the latest version (v3.1.3).

**Comment by rubel** [comment]
Thanks for quick update. Never expected you will response so quickly.
And yes...the fix worked here as well :)

Thanks buddy
